language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - if ["$TRAVIS_OS_NAME" = "windows"]; then mingw32-make && mingw32-make test else make && make test

notifications:
  irc:
    channels:
      - "chat.freenode.net##capybara"
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
    on_success: change # default: always
    on_failure: always # default: always
